collections:
  news:
    output: true
    permalink: pretty 
    name: News
  projects:
    output: true
    permalink: simple 
    name: Projects
  guides:
    output: true
    permalink: simple 
    name: Guides
